
- name: install gnupg2
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - gnupg2
    - htop
    - git-all
    
- name: ensure that GPG key for RVM is installed
  command: gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
  args:
    creates: /root/.gnupg/secring.gpg
- name: install rvm with ruby and rails
  shell: "curl -sSL https://get.rvm.io | bash -s stable --rails"
  args:
    creates: /usr/local/rvm

- git:
    repo: https://github.com/ehabzaki/blogOnRails.git
    dest: /home/vagrant/blog
